import { forwardRef, useCallback, useRef, useState } from "react";
import { ShoppingCart } from "lucide-react";
import { useCartStore } from "@/stores/cartStore";
import { usePricing } from "@/lib/pricing";
import { toast } from "sonner";

interface MobileGameTileProps {
  /** Kinguin product id, required for checkout. */
  kinguinId: number;
  title: string;
  image: string;
  /** EUR sell price; converted to DKK for display + cart. */
  price: number;
  /** EUR original price. */
  originalPrice?: number;
  marginPercent?: number | null;
  platform: string;
  /** "Steam · Europa" — falls back to the platform alone. */
  meta?: string;
  discount?: number;
  onClick: () => void;
}

/**
 * Mobile product tile — the card spec, at tile size.
 *
 * The star rating is gone. It was generated by hashing the product id into a
 * number between 4.5 and 5.0, so every game in the catalogue displayed an
 * invented review score. Fake ratings are the one piece of decoration that can
 * get a Danish shop in real trouble.
 *
 * Also removed: the second badge over the cover, the gradient wash, and the
 * sparkle that rotated forever on large discounts.
 */
const MobileGameTile = forwardRef<HTMLDivElement, MobileGameTileProps>(
  ({ kinguinId, title, image, price, originalPrice, marginPercent, platform, meta, discount, onClick }, ref) => {
    const addItem = useCartStore((state) => state.addItem);
    const { getPrice, formatDKK } = usePricing();
    const priceDkk = getPrice(price, marginPercent);
    const originalDkk = originalPrice ? getPrice(originalPrice, marginPercent) : 0;
    const pointerStartRef = useRef<{ x: number; y: number; time: number } | null>(null);
    const [isPressed, setIsPressed] = useState(false);

    const handleAddToCart = useCallback(
      (e: React.MouseEvent) => {
        e.stopPropagation();
        e.preventDefault();
        addItem({
          variantId: `kinguin-${kinguinId}`,
          kinguinId,
          title,
          quantity: 1,
          price: { amount: String(priceDkk), currencyCode: "DKK" },
          originalAmount: originalPrice && originalPrice > price ? String(originalDkk) : undefined,
          image: image || undefined,
          sku: `KINGUIN-${kinguinId}`,
        });
        toast.success(`${title} lagt i kurven`);
      },
      [addItem, kinguinId, title, priceDkk, originalPrice, price, originalDkk, image],
    );

    // Distinguish a tap from a scroll so the tile does not open mid-swipe.
    const handlePointerDown = (e: React.PointerEvent) => {
      pointerStartRef.current = { x: e.clientX, y: e.clientY, time: Date.now() };
      setIsPressed(true);
    };
    const handlePointerUp = (e: React.PointerEvent) => {
      setIsPressed(false);
      const start = pointerStartRef.current;
      pointerStartRef.current = null;
      if (!start) return;
      const moved = Math.hypot(e.clientX - start.x, e.clientY - start.y);
      if (moved < 10 && Date.now() - start.time < 700) {
        if (!(e.target as HTMLElement).closest("button")) onClick();
      }
    };

    const hasDiscount = discount !== undefined && discount > 0;

    return (
      <div
        ref={ref}
        onPointerDown={handlePointerDown}
        onPointerUp={handlePointerUp}
        onPointerCancel={() => setIsPressed(false)}
        className={`game-card w-full cursor-pointer text-left transition-transform duration-fast ${
          isPressed ? "scale-[0.98]" : ""
        }`}
        style={{ touchAction: "manipulation" }}
      >
        <div className="relative aspect-[3/4] overflow-hidden">
          <img
            src={image || "/placeholder.svg"}
            alt={title}
            className="h-full w-full object-cover"
            loading="lazy"
            onError={(e) => {
              e.currentTarget.src = "/placeholder.svg";
            }}
          />

          {hasDiscount && (
            <span className="num absolute left-2.5 top-2.5 rounded-md bg-destructive px-2 py-1 text-xs font-bold text-destructive-foreground">
              −{discount}&nbsp;%
            </span>
          )}

          <button
            className="absolute bottom-2.5 right-2.5 flex h-10 w-10 items-center justify-center rounded-lg border border-border bg-background/90 backdrop-blur transition-colors duration-fast active:bg-background"
            onClick={handleAddToCart}
            style={{ touchAction: "manipulation" }}
            aria-label={`Læg ${title} i kurven`}
          >
            <ShoppingCart className="h-4 w-4 text-foreground" />
          </button>
        </div>

        <div className="p-3">
          <p className="label-eyebrow text-muted-foreground">{meta || platform}</p>
          <h3 className="mt-1 line-clamp-2 text-sm font-semibold leading-snug">{title}</h3>
          <div className="mt-2 flex items-baseline gap-2">
            <span className="num text-lg font-bold text-primary">{formatDKK(priceDkk)}</span>
            {hasDiscount && originalPrice && (
              <span className="num text-xs text-muted-foreground/70 line-through">
                {formatDKK(originalDkk)}
              </span>
            )}
          </div>
        </div>
      </div>
    );
  },
);

MobileGameTile.displayName = "MobileGameTile";

export default MobileGameTile;
